In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_enrol = pd.read_csv("working_datasets/cleaned_enrolment_data.csv")

In [6]:
import datetime as dt

In [9]:
df_enrol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 983051 entries, 0 to 983050
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   date            983051 non-null  object
 1   state           983051 non-null  object
 2   district        983051 non-null  object
 3   pincode         983051 non-null  int64
 4   age_0_5         983051 non-null  int64
 5   age_5_17        983051 non-null  int64
 6   age_18_greater  983051 non-null  int64
dtypes: int64(4), object(3)
memory usage: 52.5+ MB

In [12]:
# print total number of distinct MONTH from the 'date' column, the format of dates is YYYY-MM-DD
df_enrol['date'] = pd.to_datetime(df_enrol['date'])
df_enrol['enrolment_month'] = df_enrol['date'].dt.to_period('M')
distinct_months = df_enrol['enrolment_month'].nunique()
print(f"Total number of distinct months in enrolment data: {distinct_months}")

Total number of distinct months in enrolment data: 9

In [13]:
# sorting the data frame wrt date column
df_enrol = df_enrol.sort_values(by='date')
df_enrol.head()

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,enrolment_month
890082,2025-03-02,Meghalaya,East_Khasi_Hills,793121,11,61,37,2025-03
535466,2025-03-09,Karnataka,Bangalore,560032,21,14,10,2025-03
78218,2025-03-09,Uttar_Pradesh,Kanpur_Dehat,208001,29,82,12,2025-03
66116,2025-03-09,Uttar_Pradesh,Ghaziabad,201301,25,249,16,2025-03
7879,2025-03-09,Haryana,Gurgaon,122001,18,19,13,2025-03

In [19]:
#making the changes on the actual saved csv.
df_enrol.to_csv("working_datasets/cleaned_enrolment_data.csv", index=False)

In [17]:
# now sorting the df_enrol along with the statenames, keeping the primary sorting element as the datas for better understanding
df_enrol = df_enrol.sort_values(by=['date', 'state'])

In [18]:
df_enrol

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater,enrolment_month
890082,2025-03-02,Meghalaya,East_Khasi_Hills,793121,11,61,37,2025-03
958303,2025-03-09,Bihar,Muzaffarpur,843331,20,49,12,2025-03
916894,2025-03-09,Bihar,Bhagalpur,812005,13,40,18,2025-03
965832,2025-03-09,Bihar,Darbhanga,847108,18,120,22,2025-03
962593,2025-03-09,Bihar,West_Champaran,845418,30,48,10,2025-03
...,...,...,...,...,...,...,...,...
749398,2025-12-31,West_Bengal,Hooghly,712704,0,1,0,2025-12
736425,2025-12-31,West_Bengal,Kolkata,700066,1,14,0,2025-12
736437,2025-12-31,West_Bengal,Kolkata,700066,0,1,0,2025-12
761300,2025-12-31,West_Bengal,West_Midnapore,721161,2,0,0,2025-12
778816,2025-12-31,West_Bengal,Malda,732142,1,1,1,2025-12